#!/bin/bash

while true
do
echo "Collecting log generated by sysmon.py script from AEROZ..."
date
/home/michihiro/aeroz_log_collector.sh > /home/michihiro/python-demo-collector.log
echo "Finish Collecting sysmon.py"
sleep 60
done
